/**
 *   In this module we don't have any practical's to cover but this module will cover about different logging tools why those are
 *   importent and how do you test application when it's in production
 * 
 *   Why user logs matters and when you are logging details how importent it is to care about different GDPA , HIPPA and PIA all this
 *   guidline's regarding user information
 * 
 *   Tools that we are going to cover
 * 
 *    Google Analytics
 *    Microsoft Clearity (This is lit)
 *    LogRocket
 *    Syntry 
 *    Open Telemetry
 *    
 * 
 *  Now above all tools will give you information about user events and we can add our custom events also
 * 
 *  But after Logging next importent step would be Alearting which helps us when something critical happens
 *  or something passed some threshold this is lit and even in tools like Syntry offers us the 
 *  alerting system our SMS , EMAIL SLACK AND ONCALL ALSO . ONCALL IS LIT
 * 
 *  Next after alerting and logging last step is fixing see its always upto criticality of bug like how seviour it
 *  is in my career i have done lot's of hot fixes also and 80% case we just log the bug in JIRA and then 
 *  set  version for next release
 * 
 *  SO ONE THING THESE THREE TOPICS WE ARE GOING TO COVER LOGGING , ALERTING , FIXING THIS ENTIRE MODULE IS THORITICAL BUT MUST
 *  BECAUSE WE ARE GOING TO LEARN GOOD AMOUNT OF NEW THINGS.
 */


/**                                         INTRO                 
 *        
 *    This is great interview question like suppose user facing issue in production then how will you 
 *    fix it ?
 * 
 *    Normal Ans : I will ask my support team to contact with user and then i will be on call with
 *    user see the issue in network tab and once i understand i will do the hot fix
 *    (THIS WAS THE REAL PROCESS ONE OF THE ED TECH COMPANY I WORKED FOR)
 * 
 *    PRO-ANSWER : IN OUR APLLICATION WE ALSO EACH LOGGING AND MONITORING WHERE WE LOGS WHAT KIND
 *    OF ISSUES USER ARE FACHING AND EACH AND EVERY DEVICE INFO WHICH HELP US TO FIX ISSUES WITHOUT
 *    EVEN CONNECTING WITH USERS.
 * 
 *    THINK ABOUT MULTI LOGGING ISSUES CAN WE FIXED WITH LOGGING AND ALERTING LIKE THIS COURSE IS
 *    ACCESS FROM 5 DIFFERENT MEANS SOMETHING PHISHE IS GOING ON IN THAT CASE WE CAN BLOCK THE 
 *    ACCOUNT
 * 
 *    RIGHT SET OF LOGGING DATA CAN REALLY HELP US TO FIX ISSUES IN SPEED
 * 
 *    ALWAYS MAKE SURE YOU HAVE PII DATA OF USER ELSE YOU WILL HAVE TO PAY BIG FINE
 * 
 *    WHAT IF ERROR HAPPENS BEFORE EVEN YOUR LOGGING GET INTIATE THIS IS GOOD QUESTION
 * 
 *    TALKING ABOUT ABOVE THING SOME CAN HAVE GOOD IMPRETION IN INTERVIEWS
 * 
 *    ALWAYS ALWAYS THING ABOUT PII DON'T STORE HELL OUT OF USER DATA
 * 
 *    SO FROM INTRO WE LEARNED ABOUT LOGGING MONITORING ALERTING FIXING
 * 
 *    DARK AND LIGHT THEAM IS KIND OF FEATURE IS NOT WORKING ITS FINE IF YOU DON'T HAVE
 *    LOGGING
 * 
 *    IN SHORT IF ANY GOOD TO HAVE FEATURE DOES NOT HAVE LOGGING THEN ITS YOU DON'T NEED LOGGING
 *    FOR THOSE
 */


/**
 *                              TELEMETRY (THIS IS NEW SO GO AS DEEP AS YOU CAN)
 * 
 *      
 *      THREE STEP OF PROCESS
 * 
 *      COLLECT ==========================>  MONITOR ============================> FIX
 * 
 * 
 *      1. COLLECT 
 *          
 *        CAPTURE THE RIGHT DATA
 *           
 *            WHAT KIND OF DATA SHOULD BE CAPTURE ?
 *  
 *                - PERFOMRANCE MATRICS
 *                (WEB VITELS => LIKE HOW LONG YOUR WEB-PAGES TAKE LOAD)
 *                (API RESPONSE TIME MUST)
 *                (SUPPOSE WE HAVE SOME LOGIC LIKE IMAGE PROCESSING OR SOME ITTERATION THEN HOW LONG DOES IT TAKE)
 *                (RESOURCE TIMING LIKE IMANGES AND ALL LOAD TIME)
 *                (PAINT TIME , FRAME RATE  , NETWORK - (LIKE YOU API RESPONSE , CONNECTED NETWORK 3G/4G)) (FRAME RATE AND FRAME DROPS WE NEED TO GO DEEP INTO THIS TOPIC FOR SURE)
 *         
 *              -  RESOURCE ERROR 
 * 
 *                   5XX OR 4XX ERROR (THIS CAN TELL US HOW FREQUVITLY OUR API GETTING FAILD)
 *                   API FAILURE
 *                   NETWORK ERROR (THIS IS GOOD WE CAN MAKE DESCITION LIKE SHOULD WE SUPPORT OFLINE OR NOT)
 *                   CLIENT EXEPTION
 *                   
 * 
 *                
 *              - USER INTERACTION
 *  
 *                   CLICK  (MUST)
 *                   SCROLLING BEHAVIOURS  (THIS ONE ALSO I LIKED)
 *                   BROWSER EVENTS 
 * 
 *             - SYSTEM UTILIZATION
 *               (RESOURCE USAGE LIKE YOUR CPU AND MEMORY USAGE OF SYSTEM BECAUSE SOMETIME THOSE COULD BE THE REASON YOUR WEBAPP BECOME SLOW)  (THIS ONE IS LIT)
 * 
 * 
 *  
 *              APART FROM ALL ABOVE THINGS WE HAVE HAVE CUSTOM EVENTS ALSO AND I HAVE USED LIKE IN 90% PROJECT MAINLY FIREBASE ANALYTICS AND MIXPANEL 
 * 
 *             FROM ABOVE ALL POINTS I WAS MAINLY FOCUS OF CUSTOM EVENTS BUT PERFORMANCE MATRICS , RESOURCE ERROR , USER INTERACTION ALL THIS I FOCUSED ONLY 40 50% FROM
 *             NOW I WILL FOCUS ON THIS ALSO    
 *
 *                   
 *                  
 *        
 *       2. CLASSIFY THE DATA (HOME,DETAILS,AUTH THIS CAN BE DIFFENENT CLASSIFICATION EXAMPLE)
 * 
 * 
 *     DIFFERANT OPTIONS WE HAVE FOR LOGGING AND MONITERING (TOOLS)
 * 
 *       1. MS CLERITY (TRY ONCE IS LIT)
 *    
 *          DEMO LINK : https://clarity.microsoft.com/demo/projects/view/3t0wlogvdz/dashboard?date=Last%203%20days (INSANE)
 * 
 *         RECORDING AND HEATMAP FEATURE IS INSANE (https://clarity.microsoft.com/demo/projects/view/3t0wlogvdz/impressions?date=Last%203%20days)
 *  
 *  
 *        
 *       2. GOOGLE ANALYTICS (USED LIKE MORE THEN 15 TIMES)
 *       3. SYNTRY (MOST COMMEN USED IN INDUSTRY I HAVE USED MANY TIMES MAINLY FOR ERRORS)
 *           IF WE CARE ONLY ABOUT ERRORS I THING THIS TOOL WINS 
 * 
 *          IN SYNTRY WE MOSTLY SPEND TIME ONLY IN ERROR BUT THE PERFORMANCE TAB IS LIT
 * 
 *           https://try.sentry-demo.com/organizations/ultimate-lark/performance/  (MUST DEEP DOWN INTO THIS)
 *           ALSO SAME AS MS CLEARTY SENTRY HAS REPLAYS VIDEO ACTION OPTION
  
 *       4. LOGROCKET (NEW)
 *       5. OPEN TELEMATRY (NEW)  (CLONED DEMO BUT NOW WORKING ISSUE WITH MAKE FILE I DON'T THING ITS DIFFERENT THEN OTHER)
 *                 (https://opentelemetry.io/docs/demo/docker-deployment/)
 * 
 *    
 *   SEE NOWING ABOUT THIS DIFFERENT TOOLS IS GOOD I TRIED MS CLEARTY AND ITS HELL EASY AND TRACKS HELL AMOUT OF STUFF AND GIVE  YOU NECESSARY DATA   
 * 
 * 
 *   CORELATION ID : IF YOU HAVE MULTIPLE SYSTEM INVOLED LIKE YOUR FRONTEND CALLING API FROM BACKEND BACKEND USING SOME THIRD PARTY API SO ON SO IF ERROR OCCURS THEN IN THAT CASE WE MUST NEED TO HAVE
 *                  CORELATION ID BETWEEN THOSE SYSTEM TO TRACK ERROR EAISLY THIS ONE ALSO I NEED TO GO DEEP
 * 
 *   FEATURE FLAG CAN BE HANDLED FROM OPEN TELEMATRY I DON'T THING WE WILL REALY ON THAT WE CAN DO IT BY OUR SELF
 *       
 */



/**
 *                                                                                    ALERTING AND FIXING 
 * 
 *  
 *  TILL NOW WE LEARNED THAT HOW WE CAN USE DIFFERNT TOOLS FOR LOGGING AND WE HAVE SEEN MANY DIFFERENT DASHBOARD THIS IS FIRST PART BUT NEXT IS HOW WE ARE GOING TO MAKE IT USEFUL WHAT WE NEED TO DO ONCE
 *  WE HAVE THOSE CLASSIFIED EVENT SO THE NEXT STEP WILL BE ALEARTING.
 * 
 * 
 *    EVENT MATRICS                          ====>                       SET THRESHOLD                 =======>        THRESHOLD EXCEEDED               ========>  ALERT
 *    (YOU HAVE THAT)
 * 
 * 
 *   LET'S DIRECTLY UNDERSTAND ABOVE CASE WITH MY REAL TIME EXAMPLE WE WERE WORKING TO ONE EDTECH APP WHERE WE WE HAVE DAILY USER BASE OF AROUND 1 LAC USER NOW SUDDENTLY ONE DAY WE SEE
 *   ONLY 20 USER BUT WE GOT THIS MESSAGE TO EARLY AND WE WERE ABLE TO RESOLVE ISSUE QUICKLY BECAUSE WE HAD SERVER SIDE PERFECT LOGGING AND  HERE WHEN YOU SET THRESOLD THEN WE CAN SET 
 *   DIFFRENT TYPES OF MODE LIKE HOW YOU WANTED TO GET THE MESSAGE ONCE ANY THRESHOLD EXCESSED.
 * 
 *      NOW HERE WE NEED TO UNDERSTAND ONE THIS THAT EVERY THRESHOLD DOES NOT HAVE SAME KIND OF PRIORITY SO CAN WE CHOOSE DIFFERNT TYPE OF MODE FOR DIFFERNT THRESHOLD
 * 
 *      ON CALL -  (ONLY FOR CRITICAL THRESHOLD) (IMPORTENT STACK HOLDER GET CALL FOR SPECIFIC  THRESHOLD SYNTRY AND MOST OF LOGGING TOOLS GIVE THIS FEATURE IN THERE PREMIUM)
 * 
 *      REST OPTIONS ARE LIKE EMAIL , SMS  FOR MID LEVEL PRIORITY 
 * 
 *      IN DAY TO DAY WE MAINLY USED THRESHOLD MESSAGE WILL BE RECEIVED OVER SLACK CHANNEL AND FROM THERE WILL WILL CREATE IN JIRA TICKET AND REST WE KNOW.
 * 
 *      ALSO ATLANSIA PARENT COMPANY OF JIRA ALSO PROVIDE SOME ALERTING TOOL BUT UNDERSTAND WE DON'T NEED TO REMEBER EVERYTHING ITS JUST LIKE YOU KNOW THIS KIND OF STUFF EXISTS
 * 
 *      
 *   NOW FIRST WE HAVE DONE LOGGING THEN WE HAVE ALERTING AT LAST WE NEED TO FIX ALSO THINGS RIGHT
 * 
 *    
 *   NOW FOR FIXING STUFF EACH COMPANY HAS DIFFERENT RULES LIKE SOMETIME WE HAVE DO HOT FIX OR SOME TIME WE MAY HAVE TO ROLL BACK THEN VERSION THOSE THINGS ARE DEPEND ON WHAT KIND OF BUG WE HAVE
 * 
 *   IN 90% CASES YOUR STUFF WILL BE PLANNED FOR NEXT RELEASE AND IN RESE 10% WE MAY HAVE TO DO HOTFIX 
 * 
 *   EXAMPLE WE HAVE ISSUE IN LOGIN API AND FOR THAT API THRESHOLD REACHED THEN WE MUST HAVE PRIORITY P1 AND IT NEEDS HOT FIX
 * 
 *   BUT AT SAME TIME IF WE HAVE THRESHOLD REACHED FOR LIGHT AND DARK THEAM THEN IN THAT WE CAN ITS NOT IMPECTING THAT MUCH ON USER SO WE CAN FIX THOSE IN NEXT SPRINT   
 * 
 *   TOOL NAME OPSGINE BY ATLANSIA
 */


/**
 *  MAJOR LEARNING FROM THIS MODULE LIKE HOW IMPORTENT LOGGING , ALERING AND FIXING IS IN DAY TO DAY CODING ALSO PERFORMANCE , RESOURSE UTILIZATION EVENTS IF WE LOG ALL THIS THEN IT WILL BE HELPFUL WHEN WE 
 *  FIX THE BUGS AT THIS THIS MODULE IN THORITICAL BUT MOST IMPORTENT ALSO FIXING IS ONE PART BUT NEXT TIME IT SHOULD NOT HAPPEN FOR THAT PREVENTION ALSO NEEDED 
 * 
 *  LINTING , PROPER PR REIVEW , TYPSCRIPT AND UNIT TEST CASE THIS ARE MUST NEEDED TO BE DONE TO FIX FEW ERRORS.
 */