/**
 *  DNS : Domain Name System 
 *  REST API , GRPC , GRAPHQL  MUST KNOW COMMUNICATION PROTOCOL
 *  
 *  MOSTLY ABOVE THREE ARE THE PROTOCOL THAT WE ARE GOING TO DECIDE 
 *  WHICH ONE TO USE AND FOR THAT THERE UNDERSTANDING IS MUST
 * 
 *  NEXT BIG THING WE NEED TO LEARN HTTP-1 ,HTTP-2 AND HTTP3 WHICH ONE TO 
 *  LEVARAGE WHEN
 */

/**
 *   HOW THE WEB WORKS ?
 * 
 *   Network Tab >> Response >> First Request to domain
 *   
 *   First thing to learn here is that see mostly we are aware the when you
 *   type google.com in any browser then or computer or network does not under
 *   stand what do we mean by that in simple term COMPUTERS understand IP 
 *   ADDRESS suppose you want something to be delieved at you home then 
 *   you give you home address in english because its our way of communication
 *   but when its comes to computers they can talk with each other through
 *   IP Address.
 * 
 *   And above is the case where DNS (Domain Name System comes into picture)
 *   you type Google.com and then your network send that request to DNS
 *   and then it return IP address of the google.com. YOU CAN SAY DNS
 *   IS LIKE DIRECTORY OF YOUR DOMAIN'S
 * 
 *   Now above thing was easy and basic to understand but one thing comes into 
 *   mind like request directly does not goes to DNS in between there are few
 *   more things from where request travels like YOUR NEAR BY CELL TOWER
 *   then YOUR PHONE COMPANY and then DNS
 * 
 *   REQUEST                             REACHES             
 *   SENT FROM >>   REACHES        >>  TO PHONE COMPANY   >>   DNS FINALLY
 *   MOBILE        TO CELL TOWER
 * 
 *  NOW THE MAIN REASON TO WRITE ALL ABOVE THING IS UNDERSTAND ONLY ONE 
 *  BASIC CONCEPT LIKE WHAT IF THERE ARE SOME WEBSITE THAT ARE BLOCKED IN
 *  YOU COUNTRY IN THAT CASE WILL REQUEST STILL REACHES TO DNS AND ANSWER
 *  IS NO IT WILL BE BLOCKED BY YOUR INTERNET SERVICE PROVIDER AND WON'T
 *  EVEN GO TO THE NEXT STPES. (SIMPLY YOU WILL GET LIKE CAN NOT REACH TO 
 *  SERVER)
 * 
 *  You basically have 3 things X , Y and Z
 *  
 *  X => your domain name
 *  Y => DNS
 *  Z => SERVER WHERE WE ACTUALLY HAVE DATA
 * 
 *  FOR ABOVE X , Y AND Z BELOW IS THE WAY HOW REQUEST GOES
 * 
 *  X >> Y 
 *  Y >> X (SENDS IP ADDREESS)
 *  X >> Z (SENDS REQUEST TO SERVER WITH IP ADDRESS)
 */


/**
 *   MULTIPLE PART OF URL  
 * 
 *   https://www.google.com/xyz?id=1 
 * 
 *  Root domain (.)
 *  Top Level Domain (.edu , .com , .dev , .org)
 *  Second Level Domain (google.com , google.edu , google.dev)
 *  Third Level Domain  (www.google.com , download.google.com , sales.google.com)
 *  
 *  (ALL 4 TYPES OF DOMAIN WE MUST HAVE IDEA ABOUT THIS THINGS)
 * 
 *  AND YOU WILL UNDERSTAND IMPORTENTS OF ABOVE THING WHEN YOU UNDERSTAND THAT
 *  WE HAVE MILLIONS OF DOMAIN AND IF WE DIRECTLY SEARCH THEN ITS COSTLY OPERATION
 *  BUT WHAT IF WE SEARCH ACCORDING TO DIFFERENT DOMAINS INFO WE HAVE LIKE
 *  BASED ON TOP , SECOND AND THIRD LEVEL DOMAIN
 * 
 *  DATA CENTER : WHERE YOU HAVE LARGE NUMBER OF CUPS WITH HIGH CONFIGURATION
n * 
 * 
 *  After top level domain .com/ we will have our own defined path like /profile
 *  /users and also we need we can have query params like ?id=1 or anything
 *  these are all possible things we can have in URL importent thing to get
 *  from here is all for types of domain like root level , top level , second
 *  and third level domain.
 * 
 *  Also in above url when we talk about parts i thing we missed https but sits called protocol/schema both word are fine
 */


/**
 *  CONNECT INTERNET ACROSS THE GLOBL : (OPTICAL FIBER NETWORK)
 * 
 *   This is also intersting that how the world is connect through optical
 *   fiber network and intresting thing is all those optical fiber wires
 *   are in SEA that means we can say that countries are connected through 
 *   SEA when it comes to network 
 */

/**
 *  ISP : (INTERNET SERVICE PROVIDES) PAYS BIG ROLES IN TERMS OF NETWORKING)
 * 
 *  FIBER OPTICAL NETWORKS WORKS ALMOST ON SPEED ON LIGHT  
 */


/**
 *  WHAT BROWSER IS DOING BEFORE EVEN MAKING REQUEST
 *   
 *   Basically all four levels of caching done by browser 
 *   
 *   Browser (Cache , Services Worker)
 *   Operating System
 *   Router
 *   ISP
 * 
 *  UNDERSTAND THAT DEPENDING ON BROWSER MAX REQUEST CAN BE HANDLED PARELLERLY
 *  IS AROUND 6 TO 8
 */


/**
 *  SERVICE WORKER UNDERSTAND THIS AND MUST UNDERSTAND THERE CACHING
 */


/**
 *  AT ALL STAGE THERE IS CACHING GOING ON WE ONLY NEED TO CARE ABOUT BROWSER LEVEL
 */


/**
 *  ONE THING I NEED TO UNDERSTAND THAT WHAT DO WE MEAN WHEN WE SAY IT GOT THE 
 *  RESPONE FROM THE SERVICE WORKER AND NEVER WENT TO SERVER
 */


/**
 * GOOGLE PEERING REQUEST DIRECTLY FROM MOBILE TO GOOGLE NO NEED TO GO TO ISP
 * PROVIDER HOW DO THAT DO THAT.
 */


/***
 *  WHEN REQUEST GOES FROM CLIENT TO SERVER FEW BELOW THINGS HAPPEN
 * 
 *  CLIENT SENDS TCP REQUEST TO CHECK IF SERVER IS AVALIABLE OR NOT
 *  SERVER ACKNOLEDGE TO CLIENT AND SAY THAT HA BHAI AVALIABLE TO BEJO REQUEST KYA CHAIYE
 *  AND THIS IS WHO BOTH DO THE HANDSHAKE FIRST AND THAN ONLY COMMINICATION STARTED
 */


/***
 *   SEE WITH DIFFERERNT HTTPS PROTOCOL WE CAN HAVE DIFFERENT TYPES OF SECURITY 
 *   AND HANDSHAKE IN SOME WE MIGHT BE HAVE TO DO HANDSHAKE WITH EACH REQUEST
 *   AND IN SOME WE MIGHT HAVE TO DO IT ONCE BUT THATS NOT PART WE WILL LEARN
 *   NOW THATS SOMETHING WE WILL TAKE CARE LATER
 */

/**
 *   SO LETS FINALIZE FEW STEPS WHEN CLIENT AND SERVER COMMUNICATE WITH EACH OTHER
 * 
 *   1. CLIENT TO DNS LOOKUP (FROM HERE IT WILL GET IP ADDRESS)
 *   2. CLIENT TO SERVER (TCP HANDSHAKE HAPPEN)
 *   3. SERVER ACKNOWLEDGE THAT YES I AM AVALIABLE 
 *   4. SERVER SENDS SSL HANDSHAKE (TO EXCHNAGE CERTIFICATES SO LATER THEY WE VERIFY WITH EACH REQUEST MAINLY IN CASE OF HTTPS)
 *   5. ONCE BOTH TCP AND SSL HANDSHAKE HAPPENS THEN ONLY IT STARTS WITH COMMUNICATION WITH EACH OTHER FOR ALL OTHER REQUEST
 * 
 *   IMPORTENT THING TO LEARN HERE IS ABOUT TCP AND SSL HANDSHAKE THAT HAPPENS
 *   BEFORE REQUEST AND ALSO NOW I UNDERSTAND WHY THEY HAVE TO EXCHANGE THE
 *   CERTIFICATES.
 * 
 *   ONE MORE THING TO LEARN HERE IS THAT AFTER COMPLETING ALL ABOVE 5 STEPS ITS
 *   UPTO SERVE HOW IT WANTS TO SEND DATA LIKE IN CHUNK OR AT ONE GO FULL RESPONSE
 * 
 *   THERE IS ONE BANCHMARK THAT WE HAVE SEE TRY TO LOAD YOU FCP (FIRST CONTANT PAINT)
 *   ASAP AND NORMALLY FOR THAT 14KB DATA IS KINDA BANCHMARK FOR GOOD SEO AND ALL
 * 
 *   REGARDING FIRST CONTECT PAINT WE ARE GOING TO COVER LATER BUT THING TO LEARN 
 *   FROM HERE IS THAT WE CAN SEND DATA IN CHUNK AND ALWAYS REMEMBER THAT 14KB 
 *   BENCHMARK HOW IMPORTANT IT IT
 */


/***
 *    TILL HERE YOU GOT ALL YOU NEED LIKE HTML , CSS AND JS NOW HOW WEB PAGE RENDER ?
 * 
 *   // https://medium.com/a-layman/how-browser-works-when-rendering-a-web-page-f49c09bec475  
 *   
 *    (MUST READ ARTICAL HOW WEB PAGE RENDER) (MUST NEED TO READ TODAY)
 * 
 *   MAINLY FOUR STEPS
 * 
 *   LOADING
 *   SCRIPTING
 *   RENDERING
 *   PAINTING
 * 
 *   CSS IN RENDER BLOCKING  (BLOCKS THE RENDERING)
 *   JS IS PARSER BLOCKING (BLOCKS THE PARSING)
 * 
 * 
 *   FIRST YOU BASICALLY SEND REQUEST TO CLIENT FOR HTML
 *   IN RESPONSE YOU GET HTML CSS AND JS
 *   NOW WITH USE OF HTML BROWSER BUINGS DOM TREE
 *   AND NEW THING WITH CSS BROWSER BUINGS CSSOM TREE
 *   THEN BROWSER MERGES BOTH DOM AND CSSOM TREE AND BUILD RENDER TREE (MERGE IS NEW THING I LEARNED)
 * 
 *   TILL ABOVE THINGS ARE GOING ON JS PARSING ALSO SOMETHING WE NEED TO THING ABOUT
 *   BECAUSE ITS PARSING BLOCKING YOU CAN USE ASYC AND DEFER TO CHANGE THE BEHAVIOURS
 *   BUT THATS TOPIC FOR LATER
 * 
 *   IN SHORT TO RENDER YOUR PAGE RENDER TREE SHOULD BE COMPLETED AND
 *   JS PARSING SHOULD BE DONE ONCE ALL THIS STEPS ARE DONE THEN 
 * 
 *   LAYOUT PAINT AND COMPOSING THESE PART STARTS (MI UNDERSTAND THIS AS WELL)
 * 
 *   
 *   LAYOUT : SEE IN THIS STAGE OUR RENDER TREE IS COMPLETED AND NOW BEFORE
 *            PAINTING IT BROWSER NEED TO DRAW THE LAYOUT ITS LIKE YOU JUST
 *            BOUGHT NEW HOUSE AND ALL YOU SEE IS BLANK WALLS EVERYTHING.
 *            JUST POSITION DECIDE KRO WHAT NEEDS TO PUT WHERE 
 * 
 *   
 *   PAINTING : AFTERING LAYOUTING OR AFTER BUYING HOUSE WHAT WE DO NEXT IS 
 *              PAINTING IN CASE OF HOUSE ALSO AND BROWSER DOES THE SAME THING
 *              IT ALSO START PAINTING OUR COMPONENTS
 * 
 *   COMPOSING : ITS LIKE ONCE PAINTING DONE IN YOUR HOUSE ITS TIME TO PUT SOFA
 *               TV AND ALL THIS THINGS SAME BROWSER DOES FOR MODELS AND ALL 
 *               COMPOSING IS TRICKY ONE WE NEED TO LEARN MORE ABOUT IT
 *  
 *   ASYNC AND DEFER MUST MUST LEARN THIS TWO THINGS I HAVE ALREADY BLOG BUT DO PRACTICAL
 * 
 *  THAT'S ALL THATS HOW FIRST WEB WORKS AND THEN WEB PAGE RENDERS.
 */























