/**
 *  clear all site data LIT HEADER
 * 
 *  Dexie alternative of Index.db 
 * 
 *  Normalization : Object or Map is LIT
 * 
 *  ETAG , LAST MODIFIED , EXPIRES , MAX-AGE THIS ARE LIT (PRIORITY MATTERS)
 * 
 *  SERVICE WORKER IS SOMETHING WE NEED TO GO DEEP LIKE HELL
 * 
 *  THIS WE ARE GOING TO COVER DATABASE AND CACHING TECHNIQUIES 
 * 
 *  CURRENT UNDERSTANDING AND TOPIC UNDERSTANDING
 * 
 *  LOCAL STORAGE (60%)
 *  SESSION STORAGE (60%)
 *  COOKIES (40% MUST GO DEEP SESSION AND PERSISTANCE COOKIES)
 *  INDEX DB (30% HERE ALSO FOCUS ON DEXIE ITS WRAPPER OF INDEX DB)
 *  HTTP CACHING (50% ITS ALL ABOUT HEADER WHAT DIFFERENT HEADERS WE CAN USE FOR CACHING)
 *  API CACHING (10% GRAPHQL , REACT QUEARY ALL THIS LIBRARY)
 *  SERVICS WORKERS (0% IDEA I WILL MUST CREATE PROD LEVEL DEMO FOR THIS SAME I NEED FOR WEB WORKERS)
 *  STATE MANAGEMENT (50% HERE WE HAVE GOOD UNDERSTANDING OF REDUX AND CONTEXT WE NEED TO GO DEEPER ON OTHER)
 * 
 *  MUST COMPLETE BY DEMO BY 11 MAY
 */